name: CI
on: push
jobs:
  build:
    name: Build & test

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: ["macos-13", "macos-15", "ubuntu-24.04", "windows-2022", "windows-2025"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install --no-package-lock
      - run: npm test